### PR TITLE
Enable Debug logging

### PR DESCRIPTION
**Pull request by cskiwi**
# Proposed Changes

Enabling logging when configured so in the config

*note: Not tested*

### CODE REVIEW

**Comment by sinclairpaul** [comment]
Can you rebase as your previous PR was already merged.

**Comment by cskiwi** [comment]
> Can you rebase as your previous PR was already merged.

Should be done

**Comment by sinclairpaul** [comment]
Thanks, this will fail on linting (we use shellcheck in the build process).

With that said, I'm not really sure the benefit of doing this, is there a particular issue you were trying to troubleshoot in the app that you needed to enable this?

**Comment by cskiwi** [comment]
Yeah I'm investigating the firefly iii import and I was experiencing some issues, after checking how to enable the debug logging (otherwise you only get a 500 error response with no real message), I noticed that the option in the configuration of the addon doesn't enable the debug log.

Some more investigation in the firefly documentation & addon documentation/source code, I noticed the `log_level` was never passed on (or I didn't see it).

**Review by sinclairpaul — CHANGES_REQUESTED** [review]
```
if bashio::config.equals 'log_level' 'debug' \  
    || bashio::config.equals 'log_level' 'trace' ;then
```

This will pass the linter

**Comment by sinclairpaul** [comment]
No problem, I tested it, if you fix it I'll merge it in

**Review by sinclairpaul — APPROVED** [review]

**Comment by sinclairpaul** [comment]
Thanks @cskiwi 👍

**Pull request merged**
